[tools]
node = "24"
"npm:corepack" = "latest"
"npm:czg" = "latest"
helm = "latest"
usage="latest"
openbao="latest"

[settings]
# 自动检测 .node-version 文件来设置 Node.js 版本
idiomatic_version_file_enable_tools = ["node"]
